kind: Deployment
apiVersion: apps/v1
metadata:
  name: minikube-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikube-react-app
  template:
    metadata:
      labels:
        app: minikube-react-app
    spec:
      containers:
      - name: minikube-react-app
        image: dockerbogo/minikube-react-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: minikube-react-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: minikube-react-app